# Generated by Django 5.2 on 2025-04-17 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_customer_store_custo_last_na_e6a359_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="store_custo_last_na_e6a359_idx",
        ),
        migrations.AlterModelTable(
            name="customer",
            table=None,
        ),
    ]
