# Generated by Django 5.2 on 2025-04-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_remove_customer_store_custo_last_na_e6a359_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
